### ISSUE TITLE
23年用这个报错 node跟数据库都装了服务也开启了想不明白

### ISSUE THREAD

**Issue by PLFENG** [purpleru/AutoStudy#11]
服务启动成功 地址:http://127.0.0.1:3001
MongooseError: Operation `user.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\Program Files\AutoStudy-master\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at Connection.openUri (D:\Program Files\AutoStudy-master\node_modules\mongoose\lib\connection.js:847:32)
    at D:\Program Files\AutoStudy-master\node_modules\mongoose\lib\index.js:351:10
    at D:\Program Files\AutoStudy-master\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (D:\Program Files\AutoStudy-master\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (D:\Program Files\AutoStudy-master\node_modules\mongoose\lib\index.js:1149:10)
    at Mongoose.connect (D:\Program Files\AutoStudy-master\node_modules\mongoose\lib\index.js:350:20)
    at Object.<anonymous> (D:\Program Files\AutoStudy-master\mongo\mongodb.js:3:10)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (D:\Program Files\AutoStudy-master\server.js:12:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
数据库链接失败
MongooseError: Operation `user.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\Program Files\AutoStudy-master\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

**Comment by ahdjfjncn** [comment]
你弄好了吗

**Comment by yida39** [comment]
将mongo文件夹下mongodb.js文件里的localhost改为127.0.0.1
