### ISSUE TITLE
无法刷取视频内容

### ISSUE THREAD

**Issue by Dogitry** [purpleru/AutoStudy#16]
```
远程服务器 https://mooc1.chaoxing.com/ananas/status/b461686434b77b8c3fc3619fdcac4555?k=43103&flag=normal&_dc=1695957246039可能出现 DNS 解析错误、TCP 层的错误、或实际的 HTTP 解析错误
当前 [第一章 新中国成立和社会主义基本制度的确立] [1.3 国民经济的恢复] 中的 [1.3国民经济的恢复.mp4] 保存状态失败
undefined
D:\Users\Donnie\Desktop\shuake\AutoStudy\modules\chaoxing\api\automatic.js:232
        if (data.isPassed) {
                 ^

TypeError: Cannot read properties of undefined (reading 'isPassed')
    at Auto.saveStatus (D:\Users\Donnie\Desktop\shuake\AutoStudy\modules\chaoxing\api\automatic.js:232:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by DiyaDe** [comment]
> ```
> 远程服务器 https://mooc1.chaoxing.com/ananas/status/b461686434b77b8c3fc3619fdcac4555?k=43103&flag=normal&_dc=1695957246039可能出现 DNS 解析错误、TCP 层的错误、或实际的 HTTP 解析错误
> 当前 [第一章 新中国成立和社会主义基本制度的确立] [1.3 国民经济的恢复] 中的 [1.3国民经济的恢复.mp4] 保存状态失败
> undefined
> D:\Users\Donnie\Desktop\shuake\AutoStudy\modules\chaoxing\api\automatic.js:232
>         if (data.isPassed) {
>                  ^
> 
> TypeError: Cannot read properties of undefined (reading 'isPassed')
>     at Auto.saveStatus (D:\Users\Donnie\Desktop\shuake\AutoStudy\modules\chaoxing\api\automatic.js:232:18)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

请问你是如何登录成功的

**Comment by purpleru** [comment]
这是超星api接口无法请求出现的问题，你看看你的网络有没有问题

**Comment by zskm01** [comment]
> 这是超星api接口无法请求出现的问题，你看看你的网络有没有问题

我也碰到了这个问题,有时候刷成功了有时候就会有这个问题,网络没问题

**Comment by DiyaDe** [comment]
> > 这是超星api接口无法请求出现的问题，你看看你的网络有没有问题
> 
> 我也碰到了这个问题,有时候刷成功了有时候就会有这个问题,网络没问题

你好我想请问，你们的超新都可以登录进去吗，为什么我就显示登陆失败,请稍后重试呢，账号和密码都是对的，
